---
title: "Interactives"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: cosmo
---

Here's some plots that I made in P8105: Data Science I

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 8,
  fig.height = 7,
  fig.align = "center",
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Row {data-height=600}
-----------------------------------------------------------------------

### Chart A

```{r}
data("instacart")

plot1 = instacart |> group_by(aisle) |>
  summarize(
  n = n()) |>
  arrange(desc(n))|>
  filter( n > 10000) |>
  ggplot(aes(x = n, y = reorder(aisle, n), fill = n)) + 
  geom_col(alpha = 0.9) +
  labs(title = "Order Counts (for Aisles with >10k Orders)",
    x = "Order Count ",
    y = "Aisle") +
  viridis::scale_fill_viridis(
    breaks = c(50000, 100000, 150000),  
    labels = c("50k", "100k", "150k")
    ) +
  theme_minimal() +
  theme(
    legend.position = "right",
    plot.title = element_text(face = "bold", size = 15),
    plot.subtitle = element_text(size = 12, color = "gray25"),
    axis.text.y = element_text(size = 8, hjust = 1),
    plot.caption = element_text(size = 8, hjust = 0, color = "gray40")
    )

ggplotly(plot1)
```

Row {data-height=400}
-----------------------------------------------------------------------

Column {data-width=650}
-----------------------------------------------------------------------

### Chart B

```{r}
plot2 <- instacart |>
  group_by(aisle) |> 
  filter(n() > 10000) |>
  ungroup() |>
  group_by(aisle, order_hour_of_day, order_dow) |>
  summarise(hourly_items_per_day = n(), .groups = "drop") |>
  group_by(aisle, order_hour_of_day) |>
  summarise(mean_order_count = mean(hourly_items_per_day, na.rm = TRUE), .groups = "drop") |>
  ggplot(
    aes(
      x = order_hour_of_day, 
      y = mean_order_count, 
      color = aisle,
      group = aisle, 
      text = paste(
        "<b>Aisle:</b>", aisle,
        "<br><b>Hour:</b>", order_hour_of_day,
        "<br><b>Mean Items Ordered:</b>", scales::comma(mean_order_count, accuracy = 1)
      )
    )
  ) +
  geom_line(size = 1) + 
  labs(
    title = "Mean Item Count by Hour of Day (Per Aisle)",
    subtitle = "For aisles with >10,000 total orders",
    x = "Hour of Day (0-23)",
    y = "Mean Item Count",
    color = "Aisle" # Sets the legend title
  ) +
  theme_minimal() +
  scale_x_continuous(breaks = seq(0, 23, by = 2))


ggplotly(plot2, tooltip = "text")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart C

```{r}
top_3 <- instacart |>
  group_by(product_name) |>
  summarize(n = n(), .groups = "drop") |> 
  arrange(desc(n)) |>                 
  slice_head(n = 3)

plot3 <- instacart |>
  filter(
    product_name %in% c(
      "Banana", 
      "Bag of Organic Bananas", 
      "Organic Strawberries"
    )
  ) |>
  add_count(product_name) |>
  ggplot(
  aes(x = product_name, y = order_hour_of_day, fill = n)) +
  geom_violin(trim = TRUE) + 
  labs(
    title = "Order Density by Hour for the 3 Most Popular Items",
    x = "Product Name",
    y = "Hour of Day (0-23)",
    fill = "Total Orders"
  ) +
  theme_minimal() +
  theme(
    legend.position = "right" 
  )

ggplotly(plot3)
```
